try throw MyException;
     catch MyException: throw;
