try throw MyException;
     catch MyException: print(3);
